url: https://patspat.com
baseurl: 

# Site settings
title: BeauPatspat
email: patspat.t@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Patspat Techathanavanich
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #beau_patspat
    - title: facebook
      url: #beaupatspat
    - title: instagram
      url: #https://www.instagram.com/beaupatspat/?hl=th
    - title: linkedin
      url: #https://www.linkedin.com/in/beau-patspat-09063b72/

- name: Palit Hongsuchon
  pic: 2
  position: Lead Marketer
  social:
    - title: facebook
      url: #https://www.facebook.com/hongsuchon
    - title: twitter
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url: https://www.facebook.com/hongsuchon
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 1554/3 Sriprach Road, Thawang
  - line: Nakhon Si Thammarat, Thailand 80000

# Build settings
markdown: kramdown
permalink: pretty

include: [".well-known"]
